/**
 * Compiles src/runtime.ts (browser code) to plain JS and writes it as a string
 * constant to src/runtime.generated.ts, so renderPage can inline the exact
 * bytes that ship as runtime.js. A test fails when the two drift.
 *
 * Usage: node scripts/runtime.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import ts from 'typescript';

const src = join(import.meta.dirname, '../src');

export function compileRuntime(): string {
    const { outputText } = ts.transpileModule(readFileSync(join(src, 'runtime.ts'), 'utf8'), {
        compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.None, removeComments: true },
    });

    return outputText.replace(/^"use strict";\n/, '');
}

export const generatedModule = (script: string) =>
    `// Generated by scripts/runtime.ts from runtime.ts. Do not edit.\nexport const runtimeScript = ${JSON.stringify(script)};\n`;

if (import.meta.main) {
    writeFileSync(join(src, 'runtime.generated.ts'), generatedModule(compileRuntime()));
}
